### Setup

In [1]:
import pandas as pd
import numpy as np
import nltk
from nltk import word_tokenize
from nltk.util import ngrams
from collections import Counter
from sklearn.feature_extraction.text import CountVectorizer

### Read in data

In [2]:
elon = pd.read_csv('elon_data.csv',parse_dates=[0], infer_datetime_format=True)
elon = elon.drop(['Unnamed: 0'], axis=1)
elon = elon.dropna(axis=0)
bored_elon = pd.read_csv('bored_elon_data.csv',parse_dates=[0], infer_datetime_format=True)
bored_elon = bored_elon.drop(['Unnamed: 0'], axis=1)
bored_elon = bored_elon.dropna(axis=0)

In [3]:
elon.head()

Tweet  \
0  @RanNatanzon @Tesla @Cortica This is completel...   
1  Paid respects to Masada earlier today. Live fr...   
2  Learning how to pour flaming absinthe over a t...   
3  @IraEhrenpreis @Tesla Thanks for your support ...   
4  @TheOnion Your cruel taunts cut me deep. Deep....   

                             Date Retweets  
0  Tue Mar 20 18:47:20 +0000 2018      195  
1  Tue Mar 20 02:20:29 +0000 2018      844  
2  Mon Mar 19 18:09:26 +0000 2018      970  
3  Sun Mar 18 04:31:53 +0000 2018      157  
4  Thu Mar 15 18:46:45 +0000 2018      465

### Clean it up

In [4]:
#remove punctuation from Tweet text
elon['Tweet'] = elon['Tweet'].str.replace('[^\w\s]','')
bored_elon['Tweet'] = bored_elon['Tweet'].str.replace('[^\w\s]','')

#add in label columns for data
elon['Label'] = "Elon"
bored_elon['Label'] = "BoredElon"

#join elon and bored_elon
frames = [elon, bored_elon]
df = pd.concat(frames)

In [5]:
df.head()

Tweet  \
0  RanNatanzon Tesla Cortica This is completely f...   
1  Paid respects to Masada earlier today Live fre...   
2  Learning how to pour flaming absinthe over a t...   
3  IraEhrenpreis Tesla Thanks for your support ov...   
4  TheOnion Your cruel taunts cut me deep Deep Bu...   

                             Date Retweets Label  
0  Tue Mar 20 18:47:20 +0000 2018      195  Elon  
1  Tue Mar 20 02:20:29 +0000 2018      844  Elon  
2  Mon Mar 19 18:09:26 +0000 2018      970  Elon  
3  Sun Mar 18 04:31:53 +0000 2018      157  Elon  
4  Thu Mar 15 18:46:45 +0000 2018      465  Elon

### Split the data into training and testing sets

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df['Tweet'], df['Label'], test_size=0.25, random_state=42, stratify=df['Label'])

### Create text features from the tweets

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer
tvec = TfidfVectorizer(stop_words='english',ngram_range=(1, 4), min_df = .02, max_df=.95)
tvec.fit(X_train)

#transforming X_train, X_test and hold_out into dataframes
tweet_train = pd.DataFrame(tvec.transform(X_train).todense(), columns = tvec.get_feature_names())
tweet_test = pd.DataFrame(tvec.transform(X_test).todense(), columns = tvec.get_feature_names())


In [8]:
tweet_train.columns

Index(['amp', 'car', 'dont', 'falcon', 'good', 'just', 'launch', 'like',
       'model', 'new', 'people', 'rocket', 'rt', 'rt spacex', 'spacex',
       'tesla', 'teslamotors', 'time', 'yes'],
      dtype='object')

In [12]:
tweet_test.head()

amp  car  dont  falcon  good  just  launch  like  model  new  people  \
0  0.0  0.0   0.0     0.0   0.0   0.0     0.0   0.0    0.0  0.0     0.0   
1  0.0  0.0   0.0     0.0   0.0   0.0     0.0   0.0    0.0  0.0     0.0   
2  0.0  0.0   0.0     1.0   0.0   0.0     0.0   0.0    0.0  0.0     0.0   
3  0.0  0.0   0.0     0.0   0.0   0.0     0.0   0.0    0.0  0.0     0.0   
4  0.0  0.0   0.0     0.0   0.0   0.0     0.0   0.0    0.0  0.0     0.0   

   rocket   rt  rt spacex  spacex  tesla  teslamotors  time  yes  
0     0.0  0.0        0.0     0.0    0.0          0.0   0.0  0.0  
1     0.0  0.0        0.0     0.0    0.0          0.0   0.0  0.0  
2     0.0  0.0        0.0     0.0    0.0          0.0   0.0  0.0  
3     0.0  1.0        0.0     0.0    0.0          0.0   0.0  0.0  
4     0.0  0.0        0.0     0.0    0.0          0.0   0.0  0.0

In [10]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.linear_model import LogisticRegression

# Setup logistic regression and score train set
logreg = LogisticRegression()
logreg.fit(tweet_train, y_train)
print("Train score: ", logreg.score(tweet_train, y_train))

#using logreg on test set
y_probs = logreg.predict(tweet_test) #predict y values for X_test
print("Output for Tested Model:")
print("Confusion Matrix of Predictions: ")
print(confusion_matrix(y_test, y_probs))

#printing classification report
print("Classification Matrix: ")
print(classification_report(y_test, y_probs, target_names=["BoredElon", "Elon"]))
print("Test score: ", logreg.score(tweet_test,y_test))

Train score:  0.711085582998
Output for Tested Model:
Confusion Matrix of Predictions: 
[[ 51 317]
 [ 22 771]]
Classification Matrix: 
             precision    recall  f1-score   support

  BoredElon       0.70      0.14      0.23       368
       Elon       0.71      0.97      0.82       793

avg / total       0.71      0.71      0.63      1161

Test score:  0.708010335917


In [11]:
from sklearn import svm
# Setup svm and score train set
clf = svm.SVC(kernel='rbf', gamma=1)
clf.fit(tweet_train, y_train)  
print("Train score: ", clf.score(tweet_train, y_train))

#using logreg on test set
y_probs = clf.predict(tweet_test) #predict y values for X_test
print("Output for Tested Model:")
print("Confusion Matrix of Predictions: ")
print(confusion_matrix(y_test, y_probs))

#printing classification report
print("Classification Matrix: ")
print(classification_report(y_test, y_probs, target_names=["BoredElon", "Elon"]))
print("Test score: ", clf.score(tweet_test,y_test))

Train score:  0.712808730615
Output for Tested Model:
Confusion Matrix of Predictions: 
[[ 51 317]
 [ 23 770]]
Classification Matrix: 
             precision    recall  f1-score   support

  BoredElon       0.69      0.14      0.23       368
       Elon       0.71      0.97      0.82       793

avg / total       0.70      0.71      0.63      1161

Test score:  0.707149009475


In [12]:
trump = pd.read_csv('data.csv',parse_dates=[0], infer_datetime_format=True)
trump = trump.dropna(axis=0)
drumpf = pd.read_csv('drumpf_data.csv',parse_dates=[0], infer_datetime_format=True)
drumpf = drumpf.drop(['Unnamed: 3'], axis=1)
drumpf = drumpf.drop(['Unnamed: 4'], axis=1)
drumpf = drumpf.drop(['Unnamed: 5'], axis=1)
drumpf = drumpf.drop(['Unnamed: 6'], axis=1)
drumpf = drumpf.dropna(axis=0)

In [13]:
drumpf.head()

Tweet  \
0  My lawyers keep reminding me that you cannot c...   
1                           @KimKardashian Save us!    
2   @YaffaDina All I know is what's on the Internet    
3  I was scared to call because I thought V. Puti...   
4  I've been self-financing my tweets since 2013,...   

                             Date Retweets  
0  Tue Mar 20 18:05:05 +0000 2018        8  
1  Tue Mar 20 17:55:10 +0000 2018        0  
2  Tue Mar 20 17:54:27 +0000 2018        0  
3  Tue Mar 20 17:48:23 +0000 2018       12  
4  Tue Mar 20 17:39:46 +0000 2018        1

In [14]:
#remove punctuation from Tweet text
trump['Tweet'] = trump['Tweet'].str.replace('[^\w\s]','')
drumpf['Tweet'] = drumpf['Tweet'].str.replace('[^\w\s]','')

#add in label columns for data
trump['Label'] = "Trump"
drumpf['Label'] = "Drumpf"

#join elon and bored_elon
frames = [trump, drumpf]
df2 = pd.concat(frames)

In [15]:
X_train, X_test, y_train, y_test = train_test_split(df2['Tweet'], df2['Label'], test_size=0.25, random_state=42, stratify=df2['Label'])
tvec = TfidfVectorizer(stop_words='english',ngram_range=(1, 4), min_df = .02, max_df=.95)
tvec.fit(X_train)

#transforming X_train, X_test and hold_out into dataframes
tweet_train = pd.DataFrame(tvec.transform(X_train).todense(), columns = tvec.get_feature_names())
tweet_test = pd.DataFrame(tvec.transform(X_test).todense(), columns = tvec.get_feature_names())
#tweet_holdout = pd.DataFrame(cvec.transform(hold_total["Tweet"]).todense(),columns=cvec.get_feature_names())

In [16]:
# Setup logistic regression and score train set
logreg = LogisticRegression()
logreg.fit(tweet_train, y_train)
print("Train score: ", logreg.score(tweet_train, y_train))

#using logreg on test set
y_probs = logreg.predict(tweet_test) #predict y values for X_test
print("Output for Tested Model:")
print("Confusion Matrix of Predictions: ")
print(confusion_matrix(y_test, y_probs))

#printing classification report
print("Classification Matrix: ")
print(classification_report(y_test, y_probs, target_names=["Drumpf", "Trump"]))
print("Test score: ", logreg.score(tweet_test,y_test))

Train score:  0.707094307562
Output for Tested Model:
Confusion Matrix of Predictions: 
[[630 162]
 [324 454]]
Classification Matrix: 
             precision    recall  f1-score   support

     Drumpf       0.66      0.80      0.72       792
      Trump       0.74      0.58      0.65       778

avg / total       0.70      0.69      0.69      1570

Test score:  0.690445859873
